### ISSUE TITLE
Uncaught Error: Class "PicoDAV\WebDAV" not found

### ISSUE THREAD

**Issue by tontof** [kd2org/picodav#1]
Thanks for this amazing WebDAV server!
I needed to modify your index.php because of this error:
```
PHP Fatal error:  Uncaught Error: Class "PicoDAV\WebDAV" not found in index.php:1547
```
I've simply replace
```$properties = WebDAV::BASIC_PROPERTIES;```
by
```$properties = Server::BASIC_PROPERTIES;```

Don't know if you want me to do a PR? I guess it shoud be also modified on server.php file?

**Comment by bohwaz** [comment]
Thanks it's fixed :)
