### ISSUE TITLE
This is awesome!

### ISSUE THREAD

**Issue by mikeaustin** [kd2org/picodav#13]
I just needed a very simple web filesystem, and this works perfectly after a little bit of trial and error. Thanks for making this.

They key for me was to understand that the php script becomes the server because of .htaccess, basically proxying all requests. I added more headers to the .htaccess file to support using it on a different domain, namely localhost. I also created a subdomain on my host so that WebDAV clients would work with it. I'm using https://www.npmjs.com/package/webdav for the JS client.

I've only added the "PROPFIND" WebDAV method so far in the headers. It will need all for full support.

subdomain

```
webdav.yourhost.com -> /public_html/.../webdav (or however you configure subdomains)
```

.htaccess

```
DirectoryIndex disabled

Header add Access-Control-Allow-Headers "*"
Header add Access-Control-Allow-Origin "*"
Header add Access-Control-Allow-Methods: "GET,POST,OPTIONS,DELETE,PUT,PROPFIND"

RedirectMatch 404 \.picodav\.ini

RewriteEngine On
RewriteBase /

# Uncomment the following 2 lignes to make things a bit faster for
# downloading files, AND you don't use PicoDAV users to manage access,
# but a regular .htpasswd file and config for your web server.
#RewriteCond %{REQUEST_FILENAME} !-f [OR]
#RewriteCond %{REQUEST_METHOD} !GET

RewriteRule ^.*$ /index.php [END]
```

**Comment by bohwaz** [comment]
You're welcome, glad it is useful :)
