### ISSUE TITLE
User Login Issues with PicoDav Configuration

### ISSUE THREAD

**Issue by jolichter** [kd2org/picodav#14]
Hello, does anyone have an idea why this only works without a user entry under PHP version 8.1.27 (FastCGI) on a PLESK server?

I have created a subdomain 'webdav' on my homepage and can access the website with this configuration:
`ANONYMOUS_READ = true`

However, it does not work with the test user:
```
ANONYMOUS_READ = false
HTTP_LOG_FILE = '/httpdocs/webdav/http_requests.log'

[greta]
password = abcd
write = true
```

The password is encrypted as expected, but I cannot log in with the test user 'greta' and password 'abcd', and no http_requests.log file is generated either. I've also deactivated the Web Application Firewall (WAF) for testing, so that's not the cause.

Thanks for any tips or solutions!

**Comment by jolichter** [comment]
Update: HTTP_LOG_FILE works, I had specified an incorrect path. 

```
ANONYMOUS_READ = false
HTTP_LOG_FILE = '/var/www/vhosts/myServer/httpdocs/webdav/http_requests.log'

[greta]
password = abcd
write = true
```

PLESK ERROR LOG:
```
2024-03-16 12:57:00	Error	xxx.xxx.xxx.xxx	401	GET / HTTP/1.0		Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36	837	SSL/TLS-Zugriff für Apache
2024-03-16 12:57:00	Error	xxx.xxx.xxx.xxx	401	PROPFIND / HTTP/1.0	https://webdav.myHomepage.tld/	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36	837	SSL/TLS-Zugriff für Apache
2024-03-16 12:57:07	Error	xxx.xxx.xxx.xxx	401	PROPFIND / HTTP/1.0	https://webdav.myHomepage.tld/	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36	837	SSL/TLS-Zugriff für Apache
```

I can still only log in without a password (ANONYMOUS_READ = true).

PS: other applications such as a CMS site with additional .htpasswd protection work without any problems on the PLESK server with SSL/TLS certificate Lets Encrypt.

**Comment by jolichter** [comment]
I've installed Nextcloud on my Plesk server, but currently, I only need WebDAV. I'm considering if Nextcloud might be a bit too complex for this purpose. So I'm also testing PicoDAV, but it only works for me with a .htpasswd file. It's a pitty that the PicoDAV authentication isn't working on my server.

**Comment by bohwaz** [comment]
I am quite sure that this is a configuration error on your web server.

This might be because you are using FPM and the HTTP Authorization header is not sent to PHP, see for example: https://stackoverflow.com/questions/3663520/php-auth-user-not-set

But this is definitely not an issue of PicoDAV.

**Comment by jolichter** [comment]
Yes indeed, your link has helped and the `CGIPassAuth On` directive has solved the problem. Many thanks!

**Comment by dfrancocci** [comment]
`CGIPassAuth On` worked for me as well. Thanks for this.

**Comment by bohwaz** [comment]
Thank you, I added this to the .htaccess file shipped with picodav.
