### ISSUE TITLE
 Parse error: syntax error, unexpected identifier "version" 

### ISSUE THREAD

**Issue by eurya** [kd2org/picodav#7]
I just dropped the file "index.php" on a Infomaniak web host and I got:

` Parse error: syntax error, unexpected identifier "version" in /home/clients/.../webdav/index.php on line 2083`
Tested with PHP 8.0 / 8.1 / 8.2, same error.

With PHP 7.4, I got this slightly different error:
` Parse error: syntax error, unexpected 'version' (T_STRING) in /home/clients/.../webdav/index.php on line 2083`

Thanks!

**Comment by bohwaz** [comment]
My best guess is that short open tags are enabled, and the XML code is mistaken for PHP. You should disable short open tags.

**Comment by bohwaz** [comment]
I added a fix, please try again.
