### ISSUE TITLE
Error upload large file

### ISSUE THREAD

**Issue by liviocmachado** [kd2org/picodav#8]
My server with apache, using cyberduck or transmit, upload large files return error: **request too large**

Can you help me? I already added the settings below and it didn't work.

@ini_set('post_max_size', '2G');
@ini_set('upload_max_filesize', '2G');

**Comment by bohwaz** [comment]
What is the size of the file?

You should set those settings in the .htaccess or server config directly. But this might be related to an Apache setting: https://serverfault.com/questions/926168/apache-over-ssl-request-entity-too-large-mod-security-not-installed

**Comment by liviocmachado** [comment]
1.5GB :(

**Comment by liviocmachado** [comment]
Mod Security is disabled... error in transmit: 

The server sent this message:
request too large

**Comment by bohwaz** [comment]
This is not related to mod_security but in the core of Apache: https://httpd.apache.org/docs/2.0/mod/core.html#limitrequestbody

I think the error comes from your server setup and not PHP so I don't think I can do anything here.

**Comment by liviocmachado** [comment]
@bohwaz  Thanks anyway for your attention. Would you know what you could change in my apache to test again?

**Comment by liviocmachado** [comment]
I even activated a file for logs:

=> <?xml version="1.0" encoding="utf-8"?><d:multistatus xmlns:d="DAV:" xmlns:ns0="urn:uuid:c2f41010-65b3-11d1-a29f-00aa00c14882/"><d:response><d:href>/livio/</d:href><d:propstat><d:prop><d:resourcetype><d:collection /></d:resourcetype></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat>
</d:response>
</d:multistatus>
<= PUT /livio/video teste.mp4
=> 204
